language: go
go:
- tip
branches:
  only:
  - master
  - staging
  - devel
install: go get -u -v ./...
script:
- make build
deploy:
  provider: heroku
  api_key:
    secure: lwNdVd3t819XAghRCiFtOPcJQ0qbMOHTcGljjX1n+OxOFeGmW4WMfb/fR6zYkTZ/qB2lxoWElP6RZB3D0Pw1tIOZ3Zr+stHlCbF5XQoKxptUllj4hXK6SQN+lrzKK43ipuZjWMHfzH2/m2xGBpcGb3lfS0bxV94j/XELwDO4j6kg2SgOLJfxRliwb9SriuFcHPt3qnengjtsg7bcdSlxzNpNiUF0FAVcm6ZjK+196KY6MzrLQldbkrnR/F6iVX8CcMqZTl4kZvTZtziR/JfDQ+Uh2Y9Z8MDBhp7VqoLTCFRZxm72ExvOoX+GFW1vH3PeOVasipuX4OqitSgTeskIDdTdYSnlw5iCxWrTVTBfLDZcgLcXrVozfn8KcKpfNHlfuY2/XXi88H+cYnkcDgf0aQ6Tw7IeYjj81rpjPv/Fh8UjsT9CSe9EDmw4JEVai6ybg0yatgCiTNNkofFoc/1W/Mn8Kn7n6lPd9cvDjEK0PewfgtDBUgHjI2AVK/xNynqe215B3PkHyzBd07Zgg6EnA37lnE6YkkOSYhRvHc2vbp7mcEfeXh9OiM+24IqTouvaAoWf8sa+Y0vJ9tb86h9qPb86LZhK6RWuIybNUZch+SKcYr4UQt6ZfrmmxRY7TdIUqzTaSUf0g89boLSf0Eim4XM5nwUWQ6Ip/A6JBVjpFFM=
  app: warmind-network
  on:
    repo: rking788/warmind-network
    branch: staging
