// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bungie

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie(in *jlexer.Lexer, out *ProfileUserInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "membershipType":
			out.MembershipType = int(in.Int())
		case "membershipId":
			out.MembershipID = string(in.String())
		case "displayName":
			out.DisplayName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie(out *jwriter.Writer, in ProfileUserInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MembershipType != 0 {
		const prefix string = ",\"membershipType\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.MembershipType))
	}
	if in.MembershipID != "" {
		const prefix string = ",\"membershipId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MembershipID))
	}
	if in.DisplayName != "" {
		const prefix string = ",\"displayName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DisplayName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProfileUserInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfileUserInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProfileUserInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfileUserInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie1(in *jlexer.Lexer, out *ProfilePayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				if out.Data == nil {
					out.Data = new(ProfileData)
				}
				(*out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie1(out *jwriter.Writer, in ProfilePayload) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Data != nil {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProfilePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfilePayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProfilePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfilePayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie1(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie2(in *jlexer.Lexer, out *ProfileData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "dateLastPlayed":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.DateLastPlayed).UnmarshalJSON(data))
			}
		case "userInfo":
			if in.IsNull() {
				in.Skip()
				out.UserInfo = nil
			} else {
				if out.UserInfo == nil {
					out.UserInfo = new(ProfileUserInfo)
				}
				(*out.UserInfo).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie2(out *jwriter.Writer, in ProfileData) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"dateLastPlayed\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.DateLastPlayed).MarshalJSON())
	}
	if in.UserInfo != nil {
		const prefix string = ",\"userInfo\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.UserInfo).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProfileData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfileData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProfileData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfileData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie2(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie3(in *jlexer.Lexer, out *MilestoneProgression) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "milestoneHash":
			out.MilestoneHash = int(in.Int())
		case "startDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StartDate).UnmarshalJSON(data))
			}
		case "endDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.EndDate).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie3(out *jwriter.Writer, in MilestoneProgression) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MilestoneHash != 0 {
		const prefix string = ",\"milestoneHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.MilestoneHash))
	}
	if true {
		const prefix string = ",\"startDate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.StartDate).MarshalJSON())
	}
	if true {
		const prefix string = ",\"endDate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.EndDate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MilestoneProgression) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MilestoneProgression) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MilestoneProgression) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MilestoneProgression) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie3(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie4(in *jlexer.Lexer, out *LinkedProfilesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseResponse = new(BaseResponse)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Response":
			if in.IsNull() {
				in.Skip()
				out.Response = nil
			} else {
				if out.Response == nil {
					out.Response = new(struct {
						Profiles      []*Profile     `json:"profiles"`
						BungieNetUser *BungieNetUser `json:"bnetMembership"`
					})
				}
				easyjsonC0e5e3f1Decode(in, out.Response)
			}
		case "ErrorCode":
			out.ErrorCode = int(in.Int())
		case "ThrottleSeconds":
			out.ThrottleSeconds = int(in.Int())
		case "ErrorStatus":
			out.ErrorStatus = string(in.String())
		case "Message":
			out.Message = string(in.String())
		case "MessageData":
			if m, ok := out.MessageData.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MessageData.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MessageData = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie4(out *jwriter.Writer, in LinkedProfilesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Response != nil {
		const prefix string = ",\"Response\":"
		first = false
		out.RawString(prefix[1:])
		easyjsonC0e5e3f1Encode(out, *in.Response)
	}
	if in.ErrorCode != 0 {
		const prefix string = ",\"ErrorCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ErrorCode))
	}
	if in.ThrottleSeconds != 0 {
		const prefix string = ",\"ThrottleSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThrottleSeconds))
	}
	if in.ErrorStatus != "" {
		const prefix string = ",\"ErrorStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ErrorStatus))
	}
	if in.Message != "" {
		const prefix string = ",\"Message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if in.MessageData != nil {
		const prefix string = ",\"MessageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.MessageData.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MessageData.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MessageData))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LinkedProfilesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LinkedProfilesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LinkedProfilesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LinkedProfilesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie4(l, v)
}
func easyjsonC0e5e3f1Decode(in *jlexer.Lexer, out *struct {
	Profiles      []*Profile     `json:"profiles"`
	BungieNetUser *BungieNetUser `json:"bnetMembership"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "profiles":
			if in.IsNull() {
				in.Skip()
				out.Profiles = nil
			} else {
				in.Delim('[')
				if out.Profiles == nil {
					if !in.IsDelim(']') {
						out.Profiles = make([]*Profile, 0, 8)
					} else {
						out.Profiles = []*Profile{}
					}
				} else {
					out.Profiles = (out.Profiles)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Profile
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Profile)
						}
						easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie5(in, v1)
					}
					out.Profiles = append(out.Profiles, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bnetMembership":
			if in.IsNull() {
				in.Skip()
				out.BungieNetUser = nil
			} else {
				if out.BungieNetUser == nil {
					out.BungieNetUser = new(BungieNetUser)
				}
				(*out.BungieNetUser).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode(out *jwriter.Writer, in struct {
	Profiles      []*Profile     `json:"profiles"`
	BungieNetUser *BungieNetUser `json:"bnetMembership"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Profiles) != 0 {
		const prefix string = ",\"profiles\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Profiles {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie5(out, *v3)
				}
			}
			out.RawByte(']')
		}
	}
	if in.BungieNetUser != nil {
		const prefix string = ",\"bnetMembership\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.BungieNetUser).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie5(in *jlexer.Lexer, out *Profile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "membershipType":
			out.MembershipType = int(in.Int())
		case "membershipId":
			out.MembershipID = string(in.String())
		case "BungieNetMembershipID":
			out.BungieNetMembershipID = string(in.String())
		case "dateLastPlayed":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.DateLastPlayed).UnmarshalJSON(data))
			}
		case "displayName":
			out.DisplayName = string(in.String())
		case "Characters":
			if in.IsNull() {
				in.Skip()
				out.Characters = nil
			} else {
				in.Delim('[')
				if out.Characters == nil {
					if !in.IsDelim(']') {
						out.Characters = make(CharacterList, 0, 8)
					} else {
						out.Characters = CharacterList{}
					}
				} else {
					out.Characters = (out.Characters)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *Character
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(Character)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					out.Characters = append(out.Characters, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "AllItems":
			if in.IsNull() {
				in.Skip()
				out.AllItems = nil
			} else {
				in.Delim('[')
				if out.AllItems == nil {
					if !in.IsDelim(']') {
						out.AllItems = make(ItemList, 0, 8)
					} else {
						out.AllItems = ItemList{}
					}
				} else {
					out.AllItems = (out.AllItems)[:0]
				}
				for !in.IsDelim(']') {
					var v5 *Item
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(Item)
						}
						easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in, v5)
					}
					out.AllItems = append(out.AllItems, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Loadouts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Loadouts = make(map[string]Loadout)
				} else {
					out.Loadouts = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 Loadout
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v6 = make(Loadout)
						} else {
							v6 = nil
						}
						for !in.IsDelim('}') {
							key := EquipmentBucket(in.UintStr())
							in.WantColon()
							var v7 *Item
							if in.IsNull() {
								in.Skip()
								v7 = nil
							} else {
								if v7 == nil {
									v7 = new(Item)
								}
								easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in, v7)
							}
							(v6)[key] = v7
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Loadouts)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		case "Equipments":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Equipments = make(map[string]Equipment)
				} else {
					out.Equipments = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v8 Equipment
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v8 = make(Equipment)
						} else {
							v8 = nil
						}
						for !in.IsDelim('}') {
							key := EquipmentBucket(in.UintStr())
							in.WantColon()
							var v9 ItemList
							if in.IsNull() {
								in.Skip()
								v9 = nil
							} else {
								in.Delim('[')
								if v9 == nil {
									if !in.IsDelim(']') {
										v9 = make(ItemList, 0, 8)
									} else {
										v9 = ItemList{}
									}
								} else {
									v9 = (v9)[:0]
								}
								for !in.IsDelim(']') {
									var v10 *Item
									if in.IsNull() {
										in.Skip()
										v10 = nil
									} else {
										if v10 == nil {
											v10 = new(Item)
										}
										easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in, v10)
									}
									v9 = append(v9, v10)
									in.WantComma()
								}
								in.Delim(']')
							}
							(v8)[key] = v9
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Equipments)[key] = v8
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie5(out *jwriter.Writer, in Profile) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MembershipType != 0 {
		const prefix string = ",\"membershipType\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.MembershipType))
	}
	if in.MembershipID != "" {
		const prefix string = ",\"membershipId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MembershipID))
	}
	if in.BungieNetMembershipID != "" {
		const prefix string = ",\"BungieNetMembershipID\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.BungieNetMembershipID))
	}
	if true {
		const prefix string = ",\"dateLastPlayed\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.DateLastPlayed).MarshalJSON())
	}
	if in.DisplayName != "" {
		const prefix string = ",\"displayName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DisplayName))
	}
	if len(in.Characters) != 0 {
		const prefix string = ",\"Characters\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Characters {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil {
					out.RawString("null")
				} else {
					(*v12).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if len(in.AllItems) != 0 {
		const prefix string = ",\"AllItems\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v13, v14 := range in.AllItems {
				if v13 > 0 {
					out.RawByte(',')
				}
				if v14 == nil {
					out.RawString("null")
				} else {
					easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out, *v14)
				}
			}
			out.RawByte(']')
		}
	}
	if len(in.Loadouts) != 0 {
		const prefix string = ",\"Loadouts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Loadouts {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				if v15Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v16First := true
					for v16Name, v16Value := range v15Value {
						if v16First {
							v16First = false
						} else {
							out.RawByte(',')
						}
						out.UintStr(uint(v16Name))
						out.RawByte(':')
						if v16Value == nil {
							out.RawString("null")
						} else {
							easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out, *v16Value)
						}
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Equipments) != 0 {
		const prefix string = ",\"Equipments\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v17First := true
			for v17Name, v17Value := range in.Equipments {
				if v17First {
					v17First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v17Name))
				out.RawByte(':')
				if v17Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v18First := true
					for v18Name, v18Value := range v17Value {
						if v18First {
							v18First = false
						} else {
							out.RawByte(',')
						}
						out.UintStr(uint(v18Name))
						out.RawByte(':')
						if v18Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
							out.RawString("null")
						} else {
							out.RawByte('[')
							for v19, v20 := range v18Value {
								if v19 > 0 {
									out.RawByte(',')
								}
								if v20 == nil {
									out.RawString("null")
								} else {
									easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out, *v20)
								}
							}
							out.RawByte(']')
						}
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in *jlexer.Lexer, out *Item) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "itemHash":
			out.ItemHash = uint(in.Uint())
		case "itemInstanceId":
			out.InstanceID = string(in.String())
		case "bucketHash":
			out.BucketHash = uint(in.Uint())
		case "lockable":
			out.Lockable = bool(in.Bool())
		case "bindStatus":
			out.BindStatus = int(in.Int())
		case "state":
			out.State = int(in.Int())
		case "location":
			out.Location = int(in.Int())
		case "transferStatus":
			out.TransferStatus = int(in.Int())
		case "quantity":
			out.Quantity = int(in.Int())
		case "Instance":
			if in.IsNull() {
				in.Skip()
				out.Instance = nil
			} else {
				if out.Instance == nil {
					out.Instance = new(ItemInstance)
				}
				easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie7(in, out.Instance)
			}
		case "Character":
			if in.IsNull() {
				in.Skip()
				out.Character = nil
			} else {
				if out.Character == nil {
					out.Character = new(Character)
				}
				(*out.Character).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out *jwriter.Writer, in Item) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ItemHash != 0 {
		const prefix string = ",\"itemHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ItemHash))
	}
	if in.InstanceID != "" {
		const prefix string = ",\"itemInstanceId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InstanceID))
	}
	if in.BucketHash != 0 {
		const prefix string = ",\"bucketHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint(uint(in.BucketHash))
	}
	if in.Lockable {
		const prefix string = ",\"lockable\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Lockable))
	}
	if in.BindStatus != 0 {
		const prefix string = ",\"bindStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.BindStatus))
	}
	if in.State != 0 {
		const prefix string = ",\"state\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.State))
	}
	if in.Location != 0 {
		const prefix string = ",\"location\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Location))
	}
	if in.TransferStatus != 0 {
		const prefix string = ",\"transferStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TransferStatus))
	}
	if in.Quantity != 0 {
		const prefix string = ",\"quantity\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Quantity))
	}
	if in.Instance != nil {
		const prefix string = ",\"Instance\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie7(out, *in.Instance)
	}
	if in.Character != nil {
		const prefix string = ",\"Character\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Character).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie7(in *jlexer.Lexer, out *ItemInstance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "isEquipped":
			out.IsEquipped = bool(in.Bool())
		case "canEquip":
			out.CanEquip = bool(in.Bool())
		case "quality":
			out.Quality = int(in.Int())
		case "cannotEquipReason":
			out.CannotEquipReason = int(in.Int())
		case "DamageType":
			out.DamageType = int(in.Int())
		case "equipRequiredLevel":
			out.EquipRequiredLevel = int(in.Int())
		case "primaryStat":
			if in.IsNull() {
				in.Skip()
				out.PrimaryStat = nil
			} else {
				if out.PrimaryStat == nil {
					out.PrimaryStat = new(struct {
						StatHash     uint `json:"statHash"`
						Value        int  `json:"value"`
						MaximumValue int  `json:"maximumValue"`
						ItemLevel    int  `json:"itemLevel"`
					})
				}
				easyjsonC0e5e3f1Decode1(in, out.PrimaryStat)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie7(out *jwriter.Writer, in ItemInstance) {
	out.RawByte('{')
	first := true
	_ = first
	if in.IsEquipped {
		const prefix string = ",\"isEquipped\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsEquipped))
	}
	if in.CanEquip {
		const prefix string = ",\"canEquip\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.CanEquip))
	}
	if in.Quality != 0 {
		const prefix string = ",\"quality\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Quality))
	}
	if in.CannotEquipReason != 0 {
		const prefix string = ",\"cannotEquipReason\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CannotEquipReason))
	}
	if in.DamageType != 0 {
		const prefix string = ",\"DamageType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DamageType))
	}
	if in.EquipRequiredLevel != 0 {
		const prefix string = ",\"equipRequiredLevel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.EquipRequiredLevel))
	}
	if in.PrimaryStat != nil {
		const prefix string = ",\"primaryStat\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC0e5e3f1Encode1(out, *in.PrimaryStat)
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1Decode1(in *jlexer.Lexer, out *struct {
	StatHash     uint `json:"statHash"`
	Value        int  `json:"value"`
	MaximumValue int  `json:"maximumValue"`
	ItemLevel    int  `json:"itemLevel"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "statHash":
			out.StatHash = uint(in.Uint())
		case "value":
			out.Value = int(in.Int())
		case "maximumValue":
			out.MaximumValue = int(in.Int())
		case "itemLevel":
			out.ItemLevel = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode1(out *jwriter.Writer, in struct {
	StatHash     uint `json:"statHash"`
	Value        int  `json:"value"`
	MaximumValue int  `json:"maximumValue"`
	ItemLevel    int  `json:"itemLevel"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.StatHash != 0 {
		const prefix string = ",\"statHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.StatHash))
	}
	if in.Value != 0 {
		const prefix string = ",\"value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Value))
	}
	if in.MaximumValue != 0 {
		const prefix string = ",\"maximumValue\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MaximumValue))
	}
	if in.ItemLevel != 0 {
		const prefix string = ",\"itemLevel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ItemLevel))
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie8(in *jlexer.Lexer, out *ItemListPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				if out.Data == nil {
					out.Data = new(ItemListData)
				}
				(*out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie8(out *jwriter.Writer, in ItemListPayload) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Data != nil {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemListPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemListPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemListPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemListPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie8(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie9(in *jlexer.Lexer, out *ItemListData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make(ItemList, 0, 8)
					} else {
						out.Items = ItemList{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v21 *Item
					if in.IsNull() {
						in.Skip()
						v21 = nil
					} else {
						if v21 == nil {
							v21 = new(Item)
						}
						easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in, v21)
					}
					out.Items = append(out.Items, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie9(out *jwriter.Writer, in ItemListData) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Items) != 0 {
		const prefix string = ",\"items\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v22, v23 := range in.Items {
				if v22 > 0 {
					out.RawByte(',')
				}
				if v23 == nil {
					out.RawString("null")
				} else {
					easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out, *v23)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemListData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemListData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemListData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemListData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie9(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie10(in *jlexer.Lexer, out *ItemInstanceData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Data = make(map[string]*ItemInstance)
				} else {
					out.Data = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v24 *ItemInstance
					if in.IsNull() {
						in.Skip()
						v24 = nil
					} else {
						if v24 == nil {
							v24 = new(ItemInstance)
						}
						easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie7(in, v24)
					}
					(out.Data)[key] = v24
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie10(out *jwriter.Writer, in ItemInstanceData) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v25First := true
			for v25Name, v25Value := range in.Data {
				if v25First {
					v25First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v25Name))
				out.RawByte(':')
				if v25Value == nil {
					out.RawString("null")
				} else {
					easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie7(out, *v25Value)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemInstanceData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemInstanceData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemInstanceData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemInstanceData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie10(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie11(in *jlexer.Lexer, out *ItemComponents) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "instances":
			if in.IsNull() {
				in.Skip()
				out.Instances = nil
			} else {
				if out.Instances == nil {
					out.Instances = new(ItemInstanceData)
				}
				(*out.Instances).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie11(out *jwriter.Writer, in ItemComponents) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Instances != nil {
		const prefix string = ",\"instances\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Instances).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemComponents) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemComponents) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemComponents) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemComponents) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie11(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie12(in *jlexer.Lexer, out *GetProfileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseResponse = new(BaseResponse)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Response":
			if in.IsNull() {
				in.Skip()
				out.Response = nil
			} else {
				if out.Response == nil {
					out.Response = new(GetProfilePayload)
				}
				(*out.Response).UnmarshalEasyJSON(in)
			}
		case "ErrorCode":
			out.ErrorCode = int(in.Int())
		case "ThrottleSeconds":
			out.ThrottleSeconds = int(in.Int())
		case "ErrorStatus":
			out.ErrorStatus = string(in.String())
		case "Message":
			out.Message = string(in.String())
		case "MessageData":
			if m, ok := out.MessageData.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MessageData.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MessageData = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie12(out *jwriter.Writer, in GetProfileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Response != nil {
		const prefix string = ",\"Response\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Response).MarshalEasyJSON(out)
	}
	if in.ErrorCode != 0 {
		const prefix string = ",\"ErrorCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ErrorCode))
	}
	if in.ThrottleSeconds != 0 {
		const prefix string = ",\"ThrottleSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThrottleSeconds))
	}
	if in.ErrorStatus != "" {
		const prefix string = ",\"ErrorStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ErrorStatus))
	}
	if in.Message != "" {
		const prefix string = ",\"Message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if in.MessageData != nil {
		const prefix string = ",\"MessageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.MessageData.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MessageData.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MessageData))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetProfileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetProfileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetProfileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetProfileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie12(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie13(in *jlexer.Lexer, out *GetProfilePayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "characterInventories":
			if in.IsNull() {
				in.Skip()
				out.CharacterInventories = nil
			} else {
				if out.CharacterInventories == nil {
					out.CharacterInventories = new(CharacterMappedItemListPayload)
				}
				(*out.CharacterInventories).UnmarshalEasyJSON(in)
			}
		case "characterEquipment":
			if in.IsNull() {
				in.Skip()
				out.CharacterEquipment = nil
			} else {
				if out.CharacterEquipment == nil {
					out.CharacterEquipment = new(CharacterMappedItemListPayload)
				}
				(*out.CharacterEquipment).UnmarshalEasyJSON(in)
			}
		case "profileInventory":
			if in.IsNull() {
				in.Skip()
				out.ProfileInventory = nil
			} else {
				if out.ProfileInventory == nil {
					out.ProfileInventory = new(ItemListPayload)
				}
				(*out.ProfileInventory).UnmarshalEasyJSON(in)
			}
		case "profileCurrencies":
			if in.IsNull() {
				in.Skip()
				out.ProfileCurrencies = nil
			} else {
				if out.ProfileCurrencies == nil {
					out.ProfileCurrencies = new(ItemListPayload)
				}
				(*out.ProfileCurrencies).UnmarshalEasyJSON(in)
			}
		case "itemComponents":
			if in.IsNull() {
				in.Skip()
				out.ItemComponents = nil
			} else {
				if out.ItemComponents == nil {
					out.ItemComponents = new(ItemComponents)
				}
				(*out.ItemComponents).UnmarshalEasyJSON(in)
			}
		case "profile":
			if in.IsNull() {
				in.Skip()
				out.Profile = nil
			} else {
				if out.Profile == nil {
					out.Profile = new(ProfilePayload)
				}
				(*out.Profile).UnmarshalEasyJSON(in)
			}
		case "characters":
			if in.IsNull() {
				in.Skip()
				out.Characters = nil
			} else {
				if out.Characters == nil {
					out.Characters = new(CharacterData)
				}
				(*out.Characters).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie13(out *jwriter.Writer, in GetProfilePayload) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CharacterInventories != nil {
		const prefix string = ",\"characterInventories\":"
		first = false
		out.RawString(prefix[1:])
		(*in.CharacterInventories).MarshalEasyJSON(out)
	}
	if in.CharacterEquipment != nil {
		const prefix string = ",\"characterEquipment\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.CharacterEquipment).MarshalEasyJSON(out)
	}
	if in.ProfileInventory != nil {
		const prefix string = ",\"profileInventory\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.ProfileInventory).MarshalEasyJSON(out)
	}
	if in.ProfileCurrencies != nil {
		const prefix string = ",\"profileCurrencies\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.ProfileCurrencies).MarshalEasyJSON(out)
	}
	if in.ItemComponents != nil {
		const prefix string = ",\"itemComponents\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.ItemComponents).MarshalEasyJSON(out)
	}
	if in.Profile != nil {
		const prefix string = ",\"profile\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Profile).MarshalEasyJSON(out)
	}
	if in.Characters != nil {
		const prefix string = ",\"characters\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Characters).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetProfilePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetProfilePayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetProfilePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetProfilePayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie13(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie14(in *jlexer.Lexer, out *FactionProgression) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseProgression = new(BaseProgression)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "factionHash":
			out.FactionHash = int(in.Int())
		case "factionVendorIndex":
			out.FactionVendorIndex = int(in.Int())
		case "progressionHash":
			out.ProgressionHash = int(in.Int())
		case "dailyProgress":
			out.DailyProgress = int(in.Int())
		case "dailyLimit":
			out.DailyLimit = int(in.Int())
		case "weeklyProgress":
			out.WeeklyProgress = int(in.Int())
		case "weeklyLimit":
			out.WeeklyLimit = int(in.Int())
		case "currentProgress":
			out.CurrentProgress = int(in.Int())
		case "level":
			out.Level = int(in.Int())
		case "levelCap":
			out.LevelCap = int(in.Int())
		case "stepIndex":
			out.StepIndex = int(in.Int())
		case "progressToNextLevel":
			out.ProgressToNextLevel = int(in.Int())
		case "nextLevelAt":
			out.NextLevelAt = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie14(out *jwriter.Writer, in FactionProgression) {
	out.RawByte('{')
	first := true
	_ = first
	if in.FactionHash != 0 {
		const prefix string = ",\"factionHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.FactionHash))
	}
	if in.FactionVendorIndex != 0 {
		const prefix string = ",\"factionVendorIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.FactionVendorIndex))
	}
	if in.ProgressionHash != 0 {
		const prefix string = ",\"progressionHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ProgressionHash))
	}
	if in.DailyProgress != 0 {
		const prefix string = ",\"dailyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyProgress))
	}
	if in.DailyLimit != 0 {
		const prefix string = ",\"dailyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyLimit))
	}
	if in.WeeklyProgress != 0 {
		const prefix string = ",\"weeklyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyProgress))
	}
	if in.WeeklyLimit != 0 {
		const prefix string = ",\"weeklyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyLimit))
	}
	if in.CurrentProgress != 0 {
		const prefix string = ",\"currentProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CurrentProgress))
	}
	if in.Level != 0 {
		const prefix string = ",\"level\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Level))
	}
	if in.LevelCap != 0 {
		const prefix string = ",\"levelCap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.LevelCap))
	}
	if in.StepIndex != 0 {
		const prefix string = ",\"stepIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.StepIndex))
	}
	if in.ProgressToNextLevel != 0 {
		const prefix string = ",\"progressToNextLevel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ProgressToNextLevel))
	}
	if in.NextLevelAt != 0 {
		const prefix string = ",\"nextLevelAt\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NextLevelAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FactionProgression) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FactionProgression) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FactionProgression) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FactionProgression) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie14(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie15(in *jlexer.Lexer, out *DestinyProgression) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseProgression = new(BaseProgression)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "progressionHash":
			out.ProgressionHash = int(in.Int())
		case "dailyProgress":
			out.DailyProgress = int(in.Int())
		case "dailyLimit":
			out.DailyLimit = int(in.Int())
		case "weeklyProgress":
			out.WeeklyProgress = int(in.Int())
		case "weeklyLimit":
			out.WeeklyLimit = int(in.Int())
		case "currentProgress":
			out.CurrentProgress = int(in.Int())
		case "level":
			out.Level = int(in.Int())
		case "levelCap":
			out.LevelCap = int(in.Int())
		case "stepIndex":
			out.StepIndex = int(in.Int())
		case "progressToNextLevel":
			out.ProgressToNextLevel = int(in.Int())
		case "nextLevelAt":
			out.NextLevelAt = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie15(out *jwriter.Writer, in DestinyProgression) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ProgressionHash != 0 {
		const prefix string = ",\"progressionHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ProgressionHash))
	}
	if in.DailyProgress != 0 {
		const prefix string = ",\"dailyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyProgress))
	}
	if in.DailyLimit != 0 {
		const prefix string = ",\"dailyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyLimit))
	}
	if in.WeeklyProgress != 0 {
		const prefix string = ",\"weeklyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyProgress))
	}
	if in.WeeklyLimit != 0 {
		const prefix string = ",\"weeklyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyLimit))
	}
	if in.CurrentProgress != 0 {
		const prefix string = ",\"currentProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CurrentProgress))
	}
	if in.Level != 0 {
		const prefix string = ",\"level\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Level))
	}
	if in.LevelCap != 0 {
		const prefix string = ",\"levelCap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.LevelCap))
	}
	if in.StepIndex != 0 {
		const prefix string = ",\"stepIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.StepIndex))
	}
	if in.ProgressToNextLevel != 0 {
		const prefix string = ",\"progressToNextLevel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ProgressToNextLevel))
	}
	if in.NextLevelAt != 0 {
		const prefix string = ",\"nextLevelAt\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NextLevelAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DestinyProgression) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DestinyProgression) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DestinyProgression) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DestinyProgression) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie15(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie16(in *jlexer.Lexer, out *DestinyMembership) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "displayName":
			out.DisplayName = string(in.String())
		case "membershipType":
			out.MembershipType = int(in.Int())
		case "membershipId":
			out.MembershipID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie16(out *jwriter.Writer, in DestinyMembership) {
	out.RawByte('{')
	first := true
	_ = first
	if in.DisplayName != "" {
		const prefix string = ",\"displayName\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.DisplayName))
	}
	if in.MembershipType != 0 {
		const prefix string = ",\"membershipType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MembershipType))
	}
	if in.MembershipID != "" {
		const prefix string = ",\"membershipId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MembershipID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DestinyMembership) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DestinyMembership) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DestinyMembership) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DestinyMembership) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie16(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie17(in *jlexer.Lexer, out *CurrentUserMembershipsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseResponse = new(BaseResponse)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Response":
			if in.IsNull() {
				in.Skip()
				out.Response = nil
			} else {
				if out.Response == nil {
					out.Response = new(struct {
						DestinyMemberships []*DestinyMembership `json:"destinyMemberships"`
						BungieNetUser      *BungieNetUser       `json:"bungieNetUser"`
					})
				}
				easyjsonC0e5e3f1Decode2(in, out.Response)
			}
		case "ErrorCode":
			out.ErrorCode = int(in.Int())
		case "ThrottleSeconds":
			out.ThrottleSeconds = int(in.Int())
		case "ErrorStatus":
			out.ErrorStatus = string(in.String())
		case "Message":
			out.Message = string(in.String())
		case "MessageData":
			if m, ok := out.MessageData.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MessageData.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MessageData = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie17(out *jwriter.Writer, in CurrentUserMembershipsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Response != nil {
		const prefix string = ",\"Response\":"
		first = false
		out.RawString(prefix[1:])
		easyjsonC0e5e3f1Encode2(out, *in.Response)
	}
	if in.ErrorCode != 0 {
		const prefix string = ",\"ErrorCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ErrorCode))
	}
	if in.ThrottleSeconds != 0 {
		const prefix string = ",\"ThrottleSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThrottleSeconds))
	}
	if in.ErrorStatus != "" {
		const prefix string = ",\"ErrorStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ErrorStatus))
	}
	if in.Message != "" {
		const prefix string = ",\"Message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if in.MessageData != nil {
		const prefix string = ",\"MessageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.MessageData.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MessageData.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MessageData))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CurrentUserMembershipsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CurrentUserMembershipsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CurrentUserMembershipsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CurrentUserMembershipsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie17(l, v)
}
func easyjsonC0e5e3f1Decode2(in *jlexer.Lexer, out *struct {
	DestinyMemberships []*DestinyMembership `json:"destinyMemberships"`
	BungieNetUser      *BungieNetUser       `json:"bungieNetUser"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "destinyMemberships":
			if in.IsNull() {
				in.Skip()
				out.DestinyMemberships = nil
			} else {
				in.Delim('[')
				if out.DestinyMemberships == nil {
					if !in.IsDelim(']') {
						out.DestinyMemberships = make([]*DestinyMembership, 0, 8)
					} else {
						out.DestinyMemberships = []*DestinyMembership{}
					}
				} else {
					out.DestinyMemberships = (out.DestinyMemberships)[:0]
				}
				for !in.IsDelim(']') {
					var v26 *DestinyMembership
					if in.IsNull() {
						in.Skip()
						v26 = nil
					} else {
						if v26 == nil {
							v26 = new(DestinyMembership)
						}
						(*v26).UnmarshalEasyJSON(in)
					}
					out.DestinyMemberships = append(out.DestinyMemberships, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bungieNetUser":
			if in.IsNull() {
				in.Skip()
				out.BungieNetUser = nil
			} else {
				if out.BungieNetUser == nil {
					out.BungieNetUser = new(BungieNetUser)
				}
				(*out.BungieNetUser).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode2(out *jwriter.Writer, in struct {
	DestinyMemberships []*DestinyMembership `json:"destinyMemberships"`
	BungieNetUser      *BungieNetUser       `json:"bungieNetUser"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.DestinyMemberships) != 0 {
		const prefix string = ",\"destinyMemberships\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v27, v28 := range in.DestinyMemberships {
				if v27 > 0 {
					out.RawByte(',')
				}
				if v28 == nil {
					out.RawString("null")
				} else {
					(*v28).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if in.BungieNetUser != nil {
		const prefix string = ",\"bungieNetUser\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.BungieNetUser).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie18(in *jlexer.Lexer, out *CurrentUserMemberships) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "BungieNetUser":
			if in.IsNull() {
				in.Skip()
				out.BungieNetUser = nil
			} else {
				if out.BungieNetUser == nil {
					out.BungieNetUser = new(BungieNetUser)
				}
				(*out.BungieNetUser).UnmarshalEasyJSON(in)
			}
		case "DestinyMembership":
			if in.IsNull() {
				in.Skip()
				out.DestinyMembership = nil
			} else {
				if out.DestinyMembership == nil {
					out.DestinyMembership = new(DestinyMembership)
				}
				(*out.DestinyMembership).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie18(out *jwriter.Writer, in CurrentUserMemberships) {
	out.RawByte('{')
	first := true
	_ = first
	if in.BungieNetUser != nil {
		const prefix string = ",\"BungieNetUser\":"
		first = false
		out.RawString(prefix[1:])
		(*in.BungieNetUser).MarshalEasyJSON(out)
	}
	if in.DestinyMembership != nil {
		const prefix string = ",\"DestinyMembership\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.DestinyMembership).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CurrentUserMemberships) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CurrentUserMemberships) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CurrentUserMemberships) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CurrentUserMemberships) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie18(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie19(in *jlexer.Lexer, out *CharacterProgressionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.BaseResponse = new(BaseResponse)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Response":
			if in.IsNull() {
				in.Skip()
				out.Response = nil
			} else {
				if out.Response == nil {
					out.Response = new(struct {
						CharacterProgressions *struct {
							Data map[string]*CharacterProgression `json:"data"`
						} `json:"characterProgressions"`
					})
				}
				easyjsonC0e5e3f1Decode3(in, out.Response)
			}
		case "ErrorCode":
			out.ErrorCode = int(in.Int())
		case "ThrottleSeconds":
			out.ThrottleSeconds = int(in.Int())
		case "ErrorStatus":
			out.ErrorStatus = string(in.String())
		case "Message":
			out.Message = string(in.String())
		case "MessageData":
			if m, ok := out.MessageData.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MessageData.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MessageData = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie19(out *jwriter.Writer, in CharacterProgressionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Response != nil {
		const prefix string = ",\"Response\":"
		first = false
		out.RawString(prefix[1:])
		easyjsonC0e5e3f1Encode3(out, *in.Response)
	}
	if in.ErrorCode != 0 {
		const prefix string = ",\"ErrorCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ErrorCode))
	}
	if in.ThrottleSeconds != 0 {
		const prefix string = ",\"ThrottleSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThrottleSeconds))
	}
	if in.ErrorStatus != "" {
		const prefix string = ",\"ErrorStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ErrorStatus))
	}
	if in.Message != "" {
		const prefix string = ",\"Message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if in.MessageData != nil {
		const prefix string = ",\"MessageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.MessageData.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MessageData.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MessageData))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CharacterProgressionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CharacterProgressionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CharacterProgressionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CharacterProgressionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie19(l, v)
}
func easyjsonC0e5e3f1Decode3(in *jlexer.Lexer, out *struct {
	CharacterProgressions *struct {
		Data map[string]*CharacterProgression `json:"data"`
	} `json:"characterProgressions"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "characterProgressions":
			if in.IsNull() {
				in.Skip()
				out.CharacterProgressions = nil
			} else {
				if out.CharacterProgressions == nil {
					out.CharacterProgressions = new(struct {
						Data map[string]*CharacterProgression `json:"data"`
					})
				}
				easyjsonC0e5e3f1Decode4(in, out.CharacterProgressions)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode3(out *jwriter.Writer, in struct {
	CharacterProgressions *struct {
		Data map[string]*CharacterProgression `json:"data"`
	} `json:"characterProgressions"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CharacterProgressions != nil {
		const prefix string = ",\"characterProgressions\":"
		first = false
		out.RawString(prefix[1:])
		easyjsonC0e5e3f1Encode4(out, *in.CharacterProgressions)
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1Decode4(in *jlexer.Lexer, out *struct {
	Data map[string]*CharacterProgression `json:"data"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Data = make(map[string]*CharacterProgression)
				} else {
					out.Data = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v29 *CharacterProgression
					if in.IsNull() {
						in.Skip()
						v29 = nil
					} else {
						if v29 == nil {
							v29 = new(CharacterProgression)
						}
						(*v29).UnmarshalEasyJSON(in)
					}
					(out.Data)[key] = v29
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode4(out *jwriter.Writer, in struct {
	Data map[string]*CharacterProgression `json:"data"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v30First := true
			for v30Name, v30Value := range in.Data {
				if v30First {
					v30First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v30Name))
				out.RawByte(':')
				if v30Value == nil {
					out.RawString("null")
				} else {
					(*v30Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie20(in *jlexer.Lexer, out *CharacterProgression) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "progressions":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Progressions = make(map[string]*DestinyProgression)
				} else {
					out.Progressions = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v31 *DestinyProgression
					if in.IsNull() {
						in.Skip()
						v31 = nil
					} else {
						if v31 == nil {
							v31 = new(DestinyProgression)
						}
						(*v31).UnmarshalEasyJSON(in)
					}
					(out.Progressions)[key] = v31
					in.WantComma()
				}
				in.Delim('}')
			}
		case "factions":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Factions = make(map[string]*FactionProgression)
				} else {
					out.Factions = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v32 *FactionProgression
					if in.IsNull() {
						in.Skip()
						v32 = nil
					} else {
						if v32 == nil {
							v32 = new(FactionProgression)
						}
						(*v32).UnmarshalEasyJSON(in)
					}
					(out.Factions)[key] = v32
					in.WantComma()
				}
				in.Delim('}')
			}
		case "milestones":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Milestones = make(map[string]*MilestoneProgression)
				} else {
					out.Milestones = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v33 *MilestoneProgression
					if in.IsNull() {
						in.Skip()
						v33 = nil
					} else {
						if v33 == nil {
							v33 = new(MilestoneProgression)
						}
						(*v33).UnmarshalEasyJSON(in)
					}
					(out.Milestones)[key] = v33
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie20(out *jwriter.Writer, in CharacterProgression) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Progressions) != 0 {
		const prefix string = ",\"progressions\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v34First := true
			for v34Name, v34Value := range in.Progressions {
				if v34First {
					v34First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v34Name))
				out.RawByte(':')
				if v34Value == nil {
					out.RawString("null")
				} else {
					(*v34Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Factions) != 0 {
		const prefix string = ",\"factions\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v35First := true
			for v35Name, v35Value := range in.Factions {
				if v35First {
					v35First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v35Name))
				out.RawByte(':')
				if v35Value == nil {
					out.RawString("null")
				} else {
					(*v35Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Milestones) != 0 {
		const prefix string = ",\"milestones\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v36First := true
			for v36Name, v36Value := range in.Milestones {
				if v36First {
					v36First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v36Name))
				out.RawByte(':')
				if v36Value == nil {
					out.RawString("null")
				} else {
					(*v36Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CharacterProgression) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CharacterProgression) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CharacterProgression) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CharacterProgression) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie20(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie21(in *jlexer.Lexer, out *CharacterMappedItemListPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Data = make(map[string]*CharacterMappedItemListData)
				} else {
					out.Data = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v37 *CharacterMappedItemListData
					if in.IsNull() {
						in.Skip()
						v37 = nil
					} else {
						if v37 == nil {
							v37 = new(CharacterMappedItemListData)
						}
						(*v37).UnmarshalEasyJSON(in)
					}
					(out.Data)[key] = v37
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie21(out *jwriter.Writer, in CharacterMappedItemListPayload) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v38First := true
			for v38Name, v38Value := range in.Data {
				if v38First {
					v38First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v38Name))
				out.RawByte(':')
				if v38Value == nil {
					out.RawString("null")
				} else {
					(*v38Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CharacterMappedItemListPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CharacterMappedItemListPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CharacterMappedItemListPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CharacterMappedItemListPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie21(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie22(in *jlexer.Lexer, out *CharacterMappedItemListData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make(ItemList, 0, 8)
					} else {
						out.Items = ItemList{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v39 *Item
					if in.IsNull() {
						in.Skip()
						v39 = nil
					} else {
						if v39 == nil {
							v39 = new(Item)
						}
						easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie6(in, v39)
					}
					out.Items = append(out.Items, v39)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie22(out *jwriter.Writer, in CharacterMappedItemListData) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Items) != 0 {
		const prefix string = ",\"items\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v40, v41 := range in.Items {
				if v40 > 0 {
					out.RawByte(',')
				}
				if v41 == nil {
					out.RawString("null")
				} else {
					easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie6(out, *v41)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CharacterMappedItemListData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie22(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CharacterMappedItemListData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie22(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CharacterMappedItemListData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie22(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CharacterMappedItemListData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie22(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie23(in *jlexer.Lexer, out *CharacterData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Data = make(CharacterMap)
				} else {
					out.Data = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v42 *Character
					if in.IsNull() {
						in.Skip()
						v42 = nil
					} else {
						if v42 == nil {
							v42 = new(Character)
						}
						(*v42).UnmarshalEasyJSON(in)
					}
					(out.Data)[key] = v42
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie23(out *jwriter.Writer, in CharacterData) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('{')
			v43First := true
			for v43Name, v43Value := range in.Data {
				if v43First {
					v43First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v43Name))
				out.RawByte(':')
				if v43Value == nil {
					out.RawString("null")
				} else {
					(*v43Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CharacterData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie23(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CharacterData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie23(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CharacterData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie23(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CharacterData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie23(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie24(in *jlexer.Lexer, out *BungieNetUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "membershipId":
			out.MembershipID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie24(out *jwriter.Writer, in BungieNetUser) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MembershipID != "" {
		const prefix string = ",\"membershipId\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MembershipID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BungieNetUser) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie24(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BungieNetUser) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie24(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BungieNetUser) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie24(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BungieNetUser) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie24(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie25(in *jlexer.Lexer, out *BaseResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ErrorCode":
			out.ErrorCode = int(in.Int())
		case "ThrottleSeconds":
			out.ThrottleSeconds = int(in.Int())
		case "ErrorStatus":
			out.ErrorStatus = string(in.String())
		case "Message":
			out.Message = string(in.String())
		case "MessageData":
			if m, ok := out.MessageData.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.MessageData.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.MessageData = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie25(out *jwriter.Writer, in BaseResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ErrorCode != 0 {
		const prefix string = ",\"ErrorCode\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ErrorCode))
	}
	if in.ThrottleSeconds != 0 {
		const prefix string = ",\"ThrottleSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThrottleSeconds))
	}
	if in.ErrorStatus != "" {
		const prefix string = ",\"ErrorStatus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ErrorStatus))
	}
	if in.Message != "" {
		const prefix string = ",\"Message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if in.MessageData != nil {
		const prefix string = ",\"MessageData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.MessageData.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.MessageData.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.MessageData))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie25(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie25(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie25(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie25(l, v)
}
func easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie26(in *jlexer.Lexer, out *BaseProgression) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "progressionHash":
			out.ProgressionHash = int(in.Int())
		case "dailyProgress":
			out.DailyProgress = int(in.Int())
		case "dailyLimit":
			out.DailyLimit = int(in.Int())
		case "weeklyProgress":
			out.WeeklyProgress = int(in.Int())
		case "weeklyLimit":
			out.WeeklyLimit = int(in.Int())
		case "currentProgress":
			out.CurrentProgress = int(in.Int())
		case "level":
			out.Level = int(in.Int())
		case "levelCap":
			out.LevelCap = int(in.Int())
		case "stepIndex":
			out.StepIndex = int(in.Int())
		case "progressToNextLevel":
			out.ProgressToNextLevel = int(in.Int())
		case "nextLevelAt":
			out.NextLevelAt = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie26(out *jwriter.Writer, in BaseProgression) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ProgressionHash != 0 {
		const prefix string = ",\"progressionHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ProgressionHash))
	}
	if in.DailyProgress != 0 {
		const prefix string = ",\"dailyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyProgress))
	}
	if in.DailyLimit != 0 {
		const prefix string = ",\"dailyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DailyLimit))
	}
	if in.WeeklyProgress != 0 {
		const prefix string = ",\"weeklyProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyProgress))
	}
	if in.WeeklyLimit != 0 {
		const prefix string = ",\"weeklyLimit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WeeklyLimit))
	}
	if in.CurrentProgress != 0 {
		const prefix string = ",\"currentProgress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CurrentProgress))
	}
	if in.Level != 0 {
		const prefix string = ",\"level\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Level))
	}
	if in.LevelCap != 0 {
		const prefix string = ",\"levelCap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.LevelCap))
	}
	if in.StepIndex != 0 {
		const prefix string = ",\"stepIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.StepIndex))
	}
	if in.ProgressToNextLevel != 0 {
		const prefix string = ",\"progressToNextLevel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ProgressToNextLevel))
	}
	if in.NextLevelAt != 0 {
		const prefix string = ",\"nextLevelAt\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NextLevelAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseProgression) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie26(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseProgression) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1EncodeGithubComRking788WarmindNetworkBungie26(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseProgression) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie26(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseProgression) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1DecodeGithubComRking788WarmindNetworkBungie26(l, v)
}
