// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bungie

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4c5cef3aDecodeGithubComRking788WarmindNetworkBungie(in *jlexer.Lexer, out *PersistedItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "itemHash":
			out.ItemHash = uint(in.Uint())
		case "itemInstanceId":
			out.InstanceID = string(in.String())
		case "bucketHash":
			out.BucketHash = uint(in.Uint())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4c5cef3aEncodeGithubComRking788WarmindNetworkBungie(out *jwriter.Writer, in PersistedItem) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ItemHash != 0 {
		const prefix string = ",\"itemHash\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ItemHash))
	}
	if in.InstanceID != "" {
		const prefix string = ",\"itemInstanceId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.InstanceID))
	}
	if in.BucketHash != 0 {
		const prefix string = ",\"bucketHash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint(uint(in.BucketHash))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersistedItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4c5cef3aEncodeGithubComRking788WarmindNetworkBungie(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersistedItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4c5cef3aEncodeGithubComRking788WarmindNetworkBungie(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersistedItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4c5cef3aDecodeGithubComRking788WarmindNetworkBungie(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersistedItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4c5cef3aDecodeGithubComRking788WarmindNetworkBungie(l, v)
}
